"""add appointment service timestamps

Revision ID: 0054278f51bd
Revises: f3a2b88f1e11
Create Date: 2026-03-20 17:16:19.003231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0054278f51bd'
down_revision = 'f3a2b88f1e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('service_completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('service_completed_at')
        batch_op.drop_column('service_started_at')

    # ### end Alembic commands ###
